# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    name: npm-publish-preview
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "%s"
          tag_message: "%s"
          create_tag: "true"
          commit_pattern: "^Publish (\\S+)"
          workspace: "."
          publish_command: "yarn"
          publish_args: "--non-interactive"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
